#!/usr/bin/env python3
"""Writes syntaxes/z80asm.tmLanguage.json and keywords.json.

The keyword lists below are what z80asm accepts. They are a copy of lists
that live in asm/src, which is the kind of copy that drifts, so
test/run.js checks them against the assembler's source on every run and
fails if either side gains or loses a word. Run this after changing them:

    python3 asm/vscode/build_grammar.py
"""
import json
import os

MNEMONICS = """ADC ADD AND BIT CALL CCF CP CPD CPDR CPI CPIR CPL DAA DEC DI DJNZ EI EX
EXX HALT IM IN INC IND INDR INI INIR JP JR LD LDD LDDR LDI LDIR NEG NOP OR
OTDR OTIR OUT OUTD OUTI POP PUSH RES RET RETI RETN RL RLA RLC RLCA RLD RR RRA
RRC RRCA RRD RST SBC SCF SET SL1 SLA SLL SRA SRL SUB XOR""".split()
DIRECTIVES = """ORG EQU DB DEFB DW DEFW DS DEFS END ASEG CSEG DSEG IF ELSE ENDIF ERROR
REPT ENDM MACRO LOCAL INCLUDE""".split()
REGISTERS = "AF' AF BC DE HL SP IXH IXL IYH IYL IX IY A B C D E H L I R".split()
CONDITIONS = "NZ NC PO PE Z P M".split()   # C is coloured as the register it is spelled like
WORD_OPERATORS = "low high eq ne lt le gt ge".split()

IDENT = r"[A-Za-z_.][A-Za-z0-9_.]*"


def alt(words):
    # Longest first, so IXH wins over IX and CPIR over CP.
    return "|".join(sorted(words, key=len, reverse=True))


def grammar():
    keyword = alt(MNEMONICS + DIRECTIVES)
    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "z80asm",
        "scopeName": "source.z80asm",
        "comment": "Generated by asm/vscode/build_grammar.py; edit that, not this file.",
        "patterns": [{"include": "#" + k} for k in (
            "comment", "definition", "string", "directive", "mnemonic", "register",
            "condition", "word-operator", "macro-arg", "number", "operator")],
        "repository": {
            "comment": {"match": ";.*$", "name": "comment.line.semicolon.z80asm"},
            "string": {"patterns": [
                {"begin": "\"", "end": "\"|$", "name": "string.quoted.double.z80asm"},
                {"comment": "A ' after a letter, digit or _ does not open a string, "
                            "exactly as the assembler reads AF'.",
                 "begin": "(?<![A-Za-z0-9_])'", "end": "'|$",
                 "name": "string.quoted.single.z80asm"}]},
            "definition": {"patterns": [
                {"comment": "name MACRO params",
                 "match": rf"^\s*({IDENT}):?\s+((?i:macro))\b",
                 "captures": {"1": {"name": "entity.name.function.macro.z80asm"},
                              "2": {"name": "storage.type.directive.z80asm"}}},
                {"comment": "name EQU expr",
                 "match": rf"^\s*({IDENT}):?\s+((?i:equ))\b",
                 "captures": {"1": {"name": "variable.other.constant.z80asm"},
                              "2": {"name": "storage.type.directive.z80asm"}}},
                {"comment": "name: at the start of a line",
                 "match": rf"^\s*({IDENT})(:)",
                 "captures": {"1": {"name": "entity.name.function.label.z80asm"},
                              "2": {"name": "punctuation.separator.label.z80asm"}}},
                {"comment": "a colon-less label: a column-0 word that is not a keyword",
                 "match": rf"^(?!(?i:(?:{keyword}))\b)([A-Za-z_][A-Za-z0-9_]*)(?=\s|;|$)",
                 "captures": {"1": {"name": "entity.name.function.label.z80asm"}}}]},
            "directive": {"match": rf"(?i)\b(?:{alt(DIRECTIVES)})\b",
                          "name": "storage.type.directive.z80asm"},
            "mnemonic": {"match": rf"(?i)\b(?:{alt(MNEMONICS)})\b",
                         "name": "keyword.other.mnemonic.z80asm"},
            "register": {"match": r"(?i)\b(?:AF'|" + alt([r for r in REGISTERS if r != "AF'"])
                                  + r")(?![A-Za-z0-9_.])",
                         "name": "variable.language.register.z80asm"},
            "condition": {"match": rf"(?i)\b(?:{alt(CONDITIONS)})\b",
                          "name": "keyword.other.condition.z80asm"},
            "word-operator": {"match": rf"(?i)\b(?:{alt(WORD_OPERATORS)})\b",
                              "name": "keyword.operator.word.z80asm"},
            "macro-arg": {"match": r"&[A-Za-z_][A-Za-z0-9_]*", "name": "variable.parameter.z80asm"},
            "number": {"patterns": [
                {"match": r"(?i)\b0x[0-9a-f]+\b", "name": "constant.numeric.hex.z80asm"},
                {"match": r"(?i)\$[0-9a-f]+\b", "name": "constant.numeric.hex.z80asm"},
                {"match": r"(?i)\b[0-9][0-9a-f]*h\b", "name": "constant.numeric.hex.z80asm"},
                {"match": r"(?i)\b[01]+b\b", "name": "constant.numeric.binary.z80asm"},
                {"match": r"\b[0-9]+\b", "name": "constant.numeric.decimal.z80asm"},
                {"comment": "$ alone is the current address",
                 "match": r"\$", "name": "variable.language.location-counter.z80asm"}]},
            "operator": {"match": r"<<|>>|<=|>=|<>|[-+*/%&|^~=<>]",
                         "name": "keyword.operator.z80asm"},
        },
    }


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "syntaxes", "z80asm.tmLanguage.json"), "w") as f:
        json.dump(grammar(), f, indent=2)
        f.write("\n")
    with open(os.path.join(here, "keywords.json"), "w") as f:
        json.dump({"mnemonics": MNEMONICS, "directives": DIRECTIVES, "registers": REGISTERS,
                   "conditions": CONDITIONS + ["C"], "word_operators": WORD_OPERATORS}, f, indent=2)
        f.write("\n")


if __name__ == "__main__":
    main()
